services:
  server:
    build:
      context: ./server
    expose:
      - "3000"
    depends_on:
      - data
    environment:
      - MONGO_URL=mongodb://data:27017/myAppDB
  
  client:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - server
  
  data:
    build:
      context: ./data
    expose:
      - "27017"
    volumes:
      - ./data/db:/data/db
      - ./data/mongo-init:/docker-entrypoint-initdb.d:ro